[package]
name = "ts"
version = "0.1.0"
edition = "2024"

[dependencies]
native_db = "0.8.1"
native_model = "0.4.20"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
uuid = { version = "1.17.0", features = ["v7"] }
